# Generated by Django 3.1.3 on 2022-11-11 13:08

import cloudinary.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_photo', cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image')),
                ('blog_name', models.CharField(max_length=60)),
                ('blog_description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', models.ImageField(upload_to='uploads/', verbose_name='Gallery Image')),
                ('image_title', models.CharField(default='DARAJA_CIF', max_length=200)),
                ('image_description', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_image', models.ImageField(upload_to='projects/', verbose_name='Project Image')),
                ('proj_title', models.CharField(max_length=200)),
                ('proj_description', tinymce.models.HTMLField()),
                ('project_date', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
