# Generated by Django 4.0.8 on 2022-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darajacifapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_intro',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
