# Generated by Django 4.0.8 on 2022-11-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darajacifapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
    ]
